server:
  port: 8082 

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
      - AuthenticationFilter
      routes:
        - id: auth-server
          uri: lb://auth-server
          predicates:
            - Path=/api/auth/**
        - id: event-service
          uri: lb://events-service
          predicates:
            - Path=/api/events/**
        - id: registration-service
          uri: lb://registrations-service
          predicates:
          - Path=/api/registrations/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: bXlfc3VwZXJfc2VjcmV0X2tleV9mb3Jfanp3dF9pbl9iYXNlNjQ= 
  expiration: 3600000 
